databases:
  - name: car-marketplace-db
    databaseName: car_marketplace_production
    user: car_marketplace

services:
  - type: web
    name: car-marketplace
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: car-marketplace-db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: RAILS_ENV
        value: production
      - key: BUNDLE_WITHOUT
        value: development:test